version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mackerel-agent-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10rqfwlsa0p6n"
s3_prefix = "mackerel-agent-lambda"
region = "ap-northeast-1"
profile = "pyto86"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
