AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mackerel agent for AWS Lambda

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/
      Handler: app.handler
      Runtime: python3.8
      Environment:
        Variables:
          MACKEREL_API_KEY: "<YOUR_API_KEY>"
      Layers:
        - !Ref Layer
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mackerel-agent-lambda
      Description: Mackerel agent for AWS Lambda
      LicenseInfo: MIT
      ContentUri: ./
      CompatibleRuntimes:
        - go1.x
        - python3.8
    Metadata:
      BuildMethod: makefile
